# 概念


卷积层对位置太敏感

我们需要一定程度的平移不变性。因为照明，物体位置，比例，外观啥的很容易变化。池化层可以缓减卷积层对位置的敏感性。

最大池化： 直接输出窗口中的max value

池化层也有padding 和 stride 

对于多输入通道的话，就对每个通道进行池化，所以channel数量相同。

# coding

In [1]:
import torch
from torch import nn

/opt/homebrew/Caskroom/miniforge/base/envs/Atari/lib/python3.9/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [4]:
def pool2d(X, pool_size, mode='max'):
    p_h, p_w = pool_size
    Y = torch.zeros((X.shape[0]-p_h+1, X.shape[1]-p_w+1))
    for i in range(Y.shape[0]):
        for j in range(Y.shape[1]):
            if mode =="max":
                Y[i, j] = X[i:i+p_h, j:j+p_w].max()
            if mode =="avg":
                Y[i, j] = X[i:i+p_h, j:j+p_w].mean()
                
    return Y

In [5]:
X = torch.tensor(range(9)).float().reshape((3,3))
pool2d(X, (2,2))

tensor([[4., 5.],
        [7., 8.]])

In [6]:
pool2d(X, (2,2), 'avg')

tensor([[2., 3.],
        [5., 6.]])

## 对于padding和stride

In [14]:
X = torch.tensor(range(16), dtype = torch.float32).reshape((1,1,4,4))
X

tensor([[[[ 0.,  1.,  2.,  3.],
          [ 4.,  5.,  6.,  7.],
          [ 8.,  9., 10., 11.],
          [12., 13., 14., 15.]]]])

In [15]:
# 调用torch的api
pool2d = nn.MaxPool2d(2)
pool2d(X)

tensor([[[[ 5.,  7.],
          [13., 15.]]]])

In [18]:
pool2d = nn.MaxPool2d((2,3), padding=1, stride=2)
pool2d(X)

tensor([[[[ 1.,  3.],
          [ 9., 11.],
          [13., 15.]]]])

In [19]:
X = torch.cat((X, X + 1), 1)
X.shape

torch.Size([1, 2, 4, 4])

In [20]:
pool2d = nn.MaxPool2d((2,3), padding=1, stride=2)
pool2d(X)

tensor([[[[ 1.,  3.],
          [ 9., 11.],
          [13., 15.]],

         [[ 2.,  4.],
          [10., 12.],
          [14., 16.]]]])